In [31]:
#!./.iris-sklearn/bin/python
import os
import json
import math

import docker
import fire

import pandas as pd
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import log_loss

from fedn.utils.helpers.helpers import get_helper, save_metadata, save_metrics

HELPER_MODULE = 'numpyhelper'
helper = get_helper(HELPER_MODULE)

model_path = "../trained_model.npz"
# model_path = "../tmp7p54msug.npz"

In [32]:
def compile_model():
    """ Compile the sklearn model.

    :return: The compiled model.
    :rtype: sklearn.linear_model._logistic.LogisticRegression
    """

    model = SGDClassifier(warm_start=True, loss='log_loss', max_iter=20, learning_rate='invscaling', eta0=0.001, random_state=100)
    model.fit([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [0, 1, 2])

    return model

def load_parameters(model_path):
    """ Load model parameters from file and populate model.

    param model_path: The path to load from.
    :type model_path: str
    :return: The loaded model.
    :rtype: torch.nn.Module
    """
    model = compile_model()
    parameters_np = np.array(helper.load(model_path))

    model.coef_ = parameters_np[:, 0:4]
    model.intercept_ = parameters_np[:, -1]

    return model

In [33]:
model = load_parameters(model_path)

In [34]:
helper.load(model_path)

[array([-0.06906662,  0.09881314, -0.08003582,  0.12005395,  0.01405938]),
 array([-0.3816695 , -0.21346732,  0.09340429,  0.23974473, -0.06696293]),
 array([ 0.03255884, -0.14899428,  0.12031783, -0.10285392, -0.03214338])]

In [35]:
np.array(parameters_np)

array([[-0.06906662,  0.09881314, -0.08003582,  0.12005395,  0.01405938],
       [-0.3816695 , -0.21346732,  0.09340429,  0.23974473, -0.06696293],
       [ 0.03255884, -0.14899428,  0.12031783, -0.10285392, -0.03214338]])